name: Publish package

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  code_quality:
    uses: ./.github/workflows/code_quality.yml

  tests:
    uses: ./.github/workflows/tests.yml

  deploy:
    needs: [code_quality, tests]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache-dependency-path: |
            ./uv.lock

      - name: Cache venv
        uses: actions/cache@v3
        with:
          path: ./.venv
          key: python-3-13-venv-${{ hashFiles('./uv.lock') }}

      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_KEY }}
        run: |
          . .venv/bin/activate
          python -m build
          twine upload dist/*
